### ISSUE TITLE
Our main methods pmap, peach and peach_with_index don't appear in RubyDoc.info

### ISSUE THREAD

**Issue by bruceadams** [bruceadams/pmap#14]
See: http://www.rubydoc.info/gems/pmap

**Comment by davidbiehl** [comment]
Huh? Perhaps because we changed the format of the comments? I thought tom-doc was pretty safe ... maybe not.

**Comment by bruceadams** [comment]
I don't know what RubyDoc picks up. My wild guess is that pmap's main methods confuse the documentation engine by not being in a class.

**Comment by davidbiehl** [comment]
That could be it. I was actually wondering about that ... it seems like we could simply do:

```
module PMap
  def pmap
    # ...
  end

  # ...
```

Instead of the `class_eval` that's being done now. Actually, I wouldn't use PMap as the module that included, maybe create a simple module like `PMap::Enumerable` that gets included into `Enumerable`?

**Comment by davidbiehl** [comment]
Now I know why, can't include a module in another module. Duh.

**Comment by bruceadams** [comment]
The docs look good now. :tada: http://www.rubydoc.info/gems/pmap/1.1.1/PMap

Thanks!
